#pragma once
// Auto-generated from dota-data vscripts/enums.json
// Updated Dota 2 game constants and enumerations

#include <cstdint>

namespace dota_constants {

    constexpr int DOTA_ITEM_INVENTORY_SIZE = 9;
    constexpr int DOTA_ITEM_MAX = 25;
    constexpr int DOTA_ITEM_STASH_MAX = 15;
    constexpr int DOTA_ITEM_STASH_MIN = 9;
    constexpr int DOTA_ITEM_STASH_SIZE = 6;
    constexpr int DOTA_MAX_ABILITIES = 40;
    constexpr int FIND_UNITS_EVERYWHERE = -1;
    constexpr int SPAWN_GROUP_HANDLE_INVALID = 0;

} // namespace dota_constants

namespace dota_game_enums {
    enum class ABILITY_TYPES : int {
        ABILITY_TYPE_BASIC = 0,
        ABILITY_TYPE_ULTIMATE = 1,
        ABILITY_TYPE_ATTRIBUTES = 2,
        ABILITY_TYPE_HIDDEN = 3,
    };
} // namespace dota_game_enums

namespace dota_game_enums {
    enum class AbilityLearnResult_t : int {
        ABILITY_CAN_BE_UPGRADED = 0,
        ABILITY_CANNOT_BE_UPGRADED_NOT_UPGRADABLE = 1,
        ABILITY_CANNOT_BE_UPGRADED_AT_MAX = 2,
        ABILITY_CANNOT_BE_UPGRADED_REQUIRES_LEVEL = 3,
        ABILITY_NOT_LEARNABLE = 4,
    };
} // namespace dota_game_enums

namespace dota_game_enums {
    enum class ActivateType : int {
        ACTIVATE_TYPE_INITIAL_CREATION = 0,
        ACTIVATE_TYPE_DATAUPDATE_CREATION = 1,
        ACTIVATE_TYPE_ONRESTORE = 2,
    };
} // namespace dota_game_enums

namespace dota_game_enums {
    enum class attackfail : int {
        DOTA_ATTACK_RECORD_FAIL_NO = 0,
        DOTA_ATTACK_RECORD_FAIL_TERRAIN_MISS = 1,
        DOTA_ATTACK_RECORD_FAIL_SOURCE_MISS = 2,
        DOTA_ATTACK_RECORD_FAIL_TARGET_EVADED = 3,
        DOTA_ATTACK_RECORD_FAIL_TARGET_INVULNERABLE = 4,
        DOTA_ATTACK_RECORD_FAIL_TARGET_OUT_OF_RANGE = 5,
        DOTA_ATTACK_RECORD_CANNOT_FAIL = 6,
        DOTA_ATTACK_RECORD_FAIL_BLOCKED_BY_OBSTRUCTION = 7,
    };
} // namespace dota_game_enums

namespace dota_game_enums {
    enum class AttributeDerivedStats : int {
        DOTA_ATTRIBUTE_STRENGTH_DAMAGE = 0,
        DOTA_ATTRIBUTE_STRENGTH_HP = 1,
        DOTA_ATTRIBUTE_STRENGTH_HP_REGEN = 2,
        DOTA_ATTRIBUTE_AGILITY_DAMAGE = 3,
        DOTA_ATTRIBUTE_AGILITY_ARMOR = 4,
        DOTA_ATTRIBUTE_AGILITY_ATTACK_SPEED = 5,
        DOTA_ATTRIBUTE_INTELLIGENCE_DAMAGE = 6,
        DOTA_ATTRIBUTE_INTELLIGENCE_MANA = 7,
        DOTA_ATTRIBUTE_INTELLIGENCE_MANA_REGEN = 8,
        DOTA_ATTRIBUTE_INTELLIGENCE_MAGIC_RESIST = 9,
        DOTA_ATTRIBUTE_ALL_DAMAGE = 10,
    };
} // namespace dota_game_enums

namespace dota_game_enums {
    enum class Attributes : int {
        DOTA_ATTRIBUTE_INVALID = -1,
        DOTA_ATTRIBUTE_STRENGTH = 0,
        DOTA_ATTRIBUTE_AGILITY = 1,
        DOTA_ATTRIBUTE_INTELLECT = 2,
        DOTA_ATTRIBUTE_ALL = 3,
        DOTA_ATTRIBUTE_MAX = 4,
    };
} // namespace dota_game_enums

namespace dota_game_enums {
    enum class CLICK_BEHAVIORS : int {
        DOTA_CLICK_BEHAVIOR_NONE = 0,
        DOTA_CLICK_BEHAVIOR_MOVE = 1,
        DOTA_CLICK_BEHAVIOR_ATTACK = 2,
        DOTA_CLICK_BEHAVIOR_CAST = 3,
        DOTA_CLICK_BEHAVIOR_DROP_ITEM = 4,
        DOTA_CLICK_BEHAVIOR_DROP_SHOP_ITEM = 5,
        DOTA_CLICK_BEHAVIOR_DRAG = 6,
        DOTA_CLICK_BEHAVIOR_LEARN_ABILITY = 7,
        DOTA_CLICK_BEHAVIOR_PATROL = 8,
        DOTA_CLICK_BEHAVIOR_VECTOR_CAST = 9,
        DOTA_CLICK_BEHAVIOR_UNUSED = 10,
        DOTA_CLICK_BEHAVIOR_RADAR = 11,
        DOTA_CLICK_BEHAVIOR_LAST = 12,
    };
} // namespace dota_game_enums

namespace dota_game_enums {
    enum class ConVarFlags : int {
        FCVAR_NONE = 0,
        FCVAR_DEVELOPMENTONLY = 2,
        FCVAR_HIDDEN = 16,
        FCVAR_PROTECTED = 32,
        FCVAR_SPONLY = 64,
        FCVAR_ARCHIVE = 128,
        FCVAR_NOTIFY = 256,
        FCVAR_USERINFO = 512,
        FCVAR_UNLOGGED = 2048,
        FCVAR_REPLICATED = 8192,
        FCVAR_CHEAT = 16384,
        FCVAR_PER_USER = 32768,
        FCVAR_DEMO = 65536,
        FCVAR_DONTRECORD = 131072,
        FCVAR_VCONSOLE_SET_FOCUS = 134217728,
    };
} // namespace dota_game_enums

namespace dota_game_enums {
    enum class DAMAGE_TYPES : int {
        DAMAGE_TYPE_NONE = 0,
        DAMAGE_TYPE_PHYSICAL = 1,
        DAMAGE_TYPE_MAGICAL = 2,
        DAMAGE_TYPE_PURE = 4,
        DAMAGE_TYPE_ALL = 7,
        DAMAGE_TYPE_HP_REMOVAL = 8,
        DAMAGE_TYPE_ABILITY_DEFINED = 16,
    };
} // namespace dota_game_enums

namespace dota_game_enums {
    enum class DamageCategory_t : int {
        DOTA_DAMAGE_CATEGORY_SPELL = 0,
        DOTA_DAMAGE_CATEGORY_ATTACK = 1,
        DOTA_DAMAGE_CATEGORY_BARRIER = 2,
    };
} // namespace dota_game_enums

namespace dota_game_enums {
    enum class DOTA_ABILITY_BEHAVIOR : int {
        DOTA_ABILITY_BEHAVIOR_LAST_RESORT_POINT = -2147483648,
        DOTA_ABILITY_BEHAVIOR_AFFECTED_BY_MUTE = 0,
        DOTA_ABILITY_BEHAVIOR_ALT_CASTABLE = 0,
        DOTA_ABILITY_BEHAVIOR_CAN_SELF_CAST = 0,
        DOTA_ABILITY_BEHAVIOR_DONT_PROC_OTHER_ABILITIES = 0,
        DOTA_ABILITY_BEHAVIOR_FORCE_KEYBIND = 0,
        DOTA_ABILITY_BEHAVIOR_FORCE_NO_INNATE_UI = 0,
        DOTA_ABILITY_BEHAVIOR_FREE_DRAW_TARGETING = 0,
        DOTA_ABILITY_BEHAVIOR_IGNORE_INVISIBLE = 0,
        DOTA_ABILITY_BEHAVIOR_IGNORE_MUTED = 0,
        DOTA_ABILITY_BEHAVIOR_IGNORE_SILENCE = 0,
        DOTA_ABILITY_BEHAVIOR_INNATE_UI = 0,
        DOTA_ABILITY_BEHAVIOR_IS_FAKE_ITEM = 0,
        DOTA_ABILITY_BEHAVIOR_ITEM_IMBUE = 0,
        DOTA_ABILITY_BEHAVIOR_NONE = 0,
        DOTA_ABILITY_BEHAVIOR_OVERSHOOT = 0,
        DOTA_ABILITY_BEHAVIOR_SHOW_IN_GUIDES = 0,
        DOTA_ABILITY_BEHAVIOR_SKIP_FOR_KEYBINDS = 0,
        DOTA_ABILITY_BEHAVIOR_SUPPRESS_ASSOCIATED_CONSUMABLE = 0,
        DOTA_ABILITY_BEHAVIOR_UNLOCKED_BY_EFFECT_INDEX = 0,
        DOTA_ABILITY_BEHAVIOR_UNSWAPPABLE = 0,
        DOTA_ABILITY_BEHAVIOR_HIDDEN = 1,
        DOTA_ABILITY_BEHAVIOR_PASSIVE = 2,
        DOTA_ABILITY_BEHAVIOR_NO_TARGET = 4,
        DOTA_ABILITY_BEHAVIOR_UNIT_TARGET = 8,
        DOTA_ABILITY_BEHAVIOR_POINT = 16,
        DOTA_ABILITY_BEHAVIOR_AOE = 32,
        DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE = 64,
        DOTA_ABILITY_BEHAVIOR_CHANNELLED = 128,
        DOTA_ABILITY_BEHAVIOR_ITEM = 256,
        DOTA_ABILITY_BEHAVIOR_TOGGLE = 512,
        DOTA_ABILITY_BEHAVIOR_DIRECTIONAL = 1024,
        DOTA_ABILITY_BEHAVIOR_IMMEDIATE = 2048,
        DOTA_ABILITY_BEHAVIOR_AUTOCAST = 4096,
        DOTA_ABILITY_BEHAVIOR_OPTIONAL_UNIT_TARGET = 8192,
        DOTA_ABILITY_BEHAVIOR_OPTIONAL_POINT = 16384,
        DOTA_ABILITY_BEHAVIOR_OPTIONAL_NO_TARGET = 32768,
        DOTA_ABILITY_BEHAVIOR_AURA = 65536,
        DOTA_ABILITY_BEHAVIOR_ATTACK = 131072,
        DOTA_ABILITY_BEHAVIOR_DONT_RESUME_MOVEMENT = 262144,
        DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES = 524288,
        DOTA_ABILITY_BEHAVIOR_UNRESTRICTED = 1048576,
        DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE = 2097152,
        DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL = 4194304,
        DOTA_ABILITY_BEHAVIOR_DONT_CANCEL_MOVEMENT = 8388608,
        DOTA_ABILITY_BEHAVIOR_DONT_ALERT_TARGET = 16777216,
        DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK = 33554432,
        DOTA_ABILITY_BEHAVIOR_NORMAL_WHEN_STOLEN = 67108864,
        DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING = 134217728,
        DOTA_ABILITY_BEHAVIOR_RUNE_TARGET = 268435456,
        // ... 2 more values
    };
} // namespace dota_game_enums

namespace dota_game_enums {
    enum class DOTA_GameState : int {
        DOTA_GAMERULES_STATE_INIT = 0,
        DOTA_GAMERULES_STATE_WAIT_FOR_PLAYERS_TO_LOAD = 1,
        DOTA_GAMERULES_STATE_CUSTOM_GAME_SETUP = 2,
        DOTA_GAMERULES_STATE_PLAYER_DRAFT = 3,
        DOTA_GAMERULES_STATE_HERO_SELECTION = 4,
        DOTA_GAMERULES_STATE_STRATEGY_TIME = 5,
        DOTA_GAMERULES_STATE_TEAM_SHOWCASE = 6,
        DOTA_GAMERULES_STATE_WAIT_FOR_MAP_TO_LOAD = 7,
        DOTA_GAMERULES_STATE_PRE_GAME = 8,
        DOTA_GAMERULES_STATE_SCENARIO_SETUP = 9,
        DOTA_GAMERULES_STATE_GAME_IN_PROGRESS = 10,
        DOTA_GAMERULES_STATE_POST_GAME = 11,
        DOTA_GAMERULES_STATE_DISCONNECT = 12,
    };
} // namespace dota_game_enums

namespace dota_game_enums {
    enum class DOTA_GC_TEAM : int {
        DOTA_GC_TEAM_GOOD_GUYS = 0,
        DOTA_GC_TEAM_BAD_GUYS = 1,
        DOTA_GC_TEAM_BROADCASTER = 2,
        DOTA_GC_TEAM_SPECTATOR = 3,
        DOTA_GC_TEAM_PLAYER_POOL = 4,
        DOTA_GC_TEAM_NOTEAM = 5,
        DOTA_GC_TEAM_CUSTOM_1 = 6,
        DOTA_GC_TEAM_CUSTOM_2 = 7,
        DOTA_GC_TEAM_CUSTOM_3 = 8,
        DOTA_GC_TEAM_CUSTOM_4 = 9,
        DOTA_GC_TEAM_CUSTOM_5 = 10,
        DOTA_GC_TEAM_CUSTOM_6 = 11,
        DOTA_GC_TEAM_CUSTOM_7 = 12,
        DOTA_GC_TEAM_CUSTOM_8 = 13,
        DOTA_GC_TEAM_NEUTRALS = 14,
    };
} // namespace dota_game_enums

namespace dota_game_enums {
    enum class DOTA_HeroPickState : int {
        DOTA_HEROPICK_STATE_NONE = 0,
        DOTA_HEROPICK_STATE_AP_SELECT = 1,
        DOTA_HEROPICK_STATE_SD_SELECT = 2,
        DOTA_HEROPICK_STATE_INTRO_SELECT_UNUSED = 3,
        DOTA_HEROPICK_STATE_RD_SELECT_UNUSED = 4,
        DOTA_HEROPICK_STATE_CM_INTRO = 5,
        DOTA_HEROPICK_STATE_CM_CAPTAINPICK = 6,
        DOTA_HEROPICK_STATE_CM_BAN1 = 7,
        DOTA_HEROPICK_STATE_CM_BAN2 = 8,
        DOTA_HEROPICK_STATE_CM_BAN3 = 9,
        DOTA_HEROPICK_STATE_CM_BAN4 = 10,
        DOTA_HEROPICK_STATE_CM_BAN5 = 11,
        DOTA_HEROPICK_STATE_CM_BAN6 = 12,
        DOTA_HEROPICK_STATE_CM_BAN7 = 13,
        DOTA_HEROPICK_STATE_CM_BAN8 = 14,
        DOTA_HEROPICK_STATE_CM_BAN9 = 15,
        DOTA_HEROPICK_STATE_CM_BAN10 = 16,
        DOTA_HEROPICK_STATE_CM_BAN11 = 17,
        DOTA_HEROPICK_STATE_CM_BAN12 = 18,
        DOTA_HEROPICK_STATE_CM_BAN13 = 19,
        DOTA_HEROPICK_STATE_CM_BAN14 = 20,
        DOTA_HEROPICK_STATE_CM_SELECT1 = 21,
        DOTA_HEROPICK_STATE_CM_SELECT2 = 22,
        DOTA_HEROPICK_STATE_CM_SELECT3 = 23,
        DOTA_HEROPICK_STATE_CM_SELECT4 = 24,
        DOTA_HEROPICK_STATE_CM_SELECT5 = 25,
        DOTA_HEROPICK_STATE_CM_SELECT6 = 26,
        DOTA_HEROPICK_STATE_CM_SELECT7 = 27,
        DOTA_HEROPICK_STATE_CM_SELECT8 = 28,
        DOTA_HEROPICK_STATE_CM_SELECT9 = 29,
        DOTA_HEROPICK_STATE_CM_SELECT10 = 30,
        DOTA_HEROPICK_STATE_CM_PICK = 31,
        DOTA_HEROPICK_STATE_AR_SELECT = 32,
        DOTA_HEROPICK_STATE_MO_SELECT = 33,
        DOTA_HEROPICK_STATE_FH_SELECT = 34,
        DOTA_HEROPICK_STATE_CD_INTRO = 35,
        DOTA_HEROPICK_STATE_CD_CAPTAINPICK = 36,
        DOTA_HEROPICK_STATE_CD_BAN1 = 37,
        DOTA_HEROPICK_STATE_CD_BAN2 = 38,
        DOTA_HEROPICK_STATE_CD_BAN3 = 39,
        DOTA_HEROPICK_STATE_CD_BAN4 = 40,
        DOTA_HEROPICK_STATE_CD_BAN5 = 41,
        DOTA_HEROPICK_STATE_CD_BAN6 = 42,
        DOTA_HEROPICK_STATE_CD_SELECT1 = 43,
        DOTA_HEROPICK_STATE_CD_SELECT2 = 44,
        DOTA_HEROPICK_STATE_CD_SELECT3 = 45,
        DOTA_HEROPICK_STATE_CD_SELECT4 = 46,
        DOTA_HEROPICK_STATE_CD_SELECT5 = 47,
        DOTA_HEROPICK_STATE_CD_SELECT6 = 48,
        DOTA_HEROPICK_STATE_CD_SELECT7 = 49,
        // ... 13 more values
    };
} // namespace dota_game_enums

namespace dota_game_enums {
    enum class DOTA_INVALID_ORDERS : int {
        DOTA_ORDER_SUCCESS = -1,
        DOTA_INVALID_ORDER_NOT_CONTROLLABLE_BY_PLAYER = 0,
        DOTA_INVALID_ORDER_UNIT_IS_NOT_NPC = 1,
        DOTA_INVALID_ORDER_BAD_ABILITY_ENTITY = 2,
        DOTA_INVALID_ORDER_UNRECOGNIZED_ORDER = 3,
        DOTA_INVALID_ORDER_ABILITY_REQUIRED = 4,
        DOTA_INVALID_ORDER_NPC_TARGET_REQUIRED = 5,
        DOTA_INVALID_ORDER_TARGET_TREE_INDEX_NOT_A_TREE = 6,
        DOTA_INVALID_ORDER_TARGET_ENTITY_INDEX_OUT_OF_RANGE = 7,
        DOTA_INVALID_ORDER_ABILITY_NOT_AN_ITEM = 8,
        DOTA_INVALID_ORDER_PHYSICAL_ITEM_TARGET_REQUIRED = 9,
        DOTA_INVALID_ORDER_RUNE_TARGET_REQUIRED = 10,
        DOTA_INVALID_ORDER_ABILITY_NOT_OWNED_BY_UNIT = 11,
        DOTA_INVALID_ORDER_ABILITY_CANT_BE_UPGRADED = 12,
        DOTA_INVALID_ORDER_NO_POINTS_FOR_ABILITY_UPGRADE = 13,
        DOTA_INVALID_ORDER_NOT_ENOUGH_MANA = 14,
        DOTA_INVALID_ORDER_ABILITY_IN_COOLDOWN = 15,
        DOTA_INVALID_ORDER_ABILITY_NOT_LEARNED = 16,
        DOTA_INVALID_ORDER_CANT_CAST_PASSIVE_ABILITY = 17,
        DOTA_INVALID_ORDER_PHANTOM_TARGET = 18,
        DOTA_INVALID_ORDER_DEAD_TARGET = 19,
        DOTA_INVALID_ORDER_UNIT_IS_DEAD = 20,
        DOTA_INVALID_ORDER_TARGET_MAGIC_IMMUNE_ENEMY = 21,
        DOTA_INVALID_ORDER_TARGET_INVULNERABLE = 22,
        DOTA_INVALID_ORDER_TARGET_ATTACK_IMMUNE = 23,
        DOTA_INVALID_ORDER_UNIT_SILENCED = 24,
        DOTA_INVALID_ORDER_ABILITY_CANT_BE_TOGGLED = 25,
        DOTA_INVALID_ORDER_TARGET_CANT_BE_SEEN = 26,
        DOTA_INVALID_ORDER_TARGET_INVISIBLE = 27,
        DOTA_INVALID_ORDER_HERO_CANT_BE_DENIED = 28,
        DOTA_INVALID_ORDER_CANT_CAST_ON_TEAMMATE = 29,
        DOTA_INVALID_ORDER_CANT_CAST_ON_ENEMY = 30,
        DOTA_INVALID_ORDER_UNIT_CANT_MOVE = 31,
        DOTA_INVALID_ORDER_CANT_CAST_ON_ATTACK_IMMUNE = 32,
        DOTA_INVALID_ORDER_PURCHASE_INVALID_ITEM = 33,
        DOTA_INVALID_ORDER_ITEM_NOT_IN_INVENTORY = 34,
        DOTA_INVALID_ORDER_ITEM_NOT_IN_UNIT_INVENTORY = 35,
        DOTA_INVALID_ORDER_TARGET_UNSELECTABLE = 36,
        DOTA_INVALID_ORDER_ITEM_NOT_IN_ACTIVE_INVENTORY = 37,
        DOTA_INVALID_ORDER_UNIT_CANT_PICK_UP_RUNES = 38,
        DOTA_INVALID_ORDER_UNIT_CANT_MANIPULATE_ITEMS = 39,
        DOTA_INVALID_ORDER_UNIT_IS_ILLUSION = 40,
        DOTA_INVALID_ORDER_UNIT_CANT_ATTACK = 41,
        DOTA_INVALID_ORDER_ITEM_CANT_BE_DROPPED = 42,
        DOTA_INVALID_ORDER_TARGET_TREE_NOT_ACTIVE = 43,
        DOTA_INVALID_ORDER_ABILITY_CANT_AUTO_CAST = 44,
        DOTA_INVALID_ORDER_TARGET_POSITION_OFF_MAP = 45,
        DOTA_INVALID_ORDER_UNIT_CANT_MOVE_TARGET_OUT_OF_RANGE = 46,
        DOTA_INVALID_ORDER_CANT_CAST_ON_HERO = 47,
        DOTA_INVALID_ORDER_CANT_CAST_ON_OTHER = 48,
        // ... 75 more values
    };
} // namespace dota_game_enums

namespace dota_game_enums {
    enum class DOTA_MOTION_CONTROLLER_PRIORITY : int {
        DOTA_MOTION_CONTROLLER_PRIORITY_LOWEST = 0,
        DOTA_MOTION_CONTROLLER_PRIORITY_LOW = 1,
        DOTA_MOTION_CONTROLLER_PRIORITY_MEDIUM = 2,
        DOTA_MOTION_CONTROLLER_PRIORITY_HIGH = 3,
        DOTA_MOTION_CONTROLLER_PRIORITY_HIGHEST = 4,
        DOTA_MOTION_CONTROLLER_PRIORITY_ULTRA = 5,
    };
} // namespace dota_game_enums

namespace dota_game_enums {
    enum class DOTA_OVERHEAD_ALERT : int {
        OVERHEAD_ALERT_GOLD = 0,
        OVERHEAD_ALERT_DENY = 1,
        OVERHEAD_ALERT_CRITICAL = 2,
        OVERHEAD_ALERT_XP = 3,
        OVERHEAD_ALERT_BONUS_SPELL_DAMAGE = 4,
        OVERHEAD_ALERT_MISS = 5,
        OVERHEAD_ALERT_DAMAGE = 6,
        OVERHEAD_ALERT_EVADE = 7,
        OVERHEAD_ALERT_BLOCK = 8,
        OVERHEAD_ALERT_BONUS_POISON_DAMAGE = 9,
        OVERHEAD_ALERT_HEAL = 10,
        OVERHEAD_ALERT_MANA_ADD = 11,
        OVERHEAD_ALERT_MANA_LOSS = 12,
        OVERHEAD_ALERT_MAGICAL_BLOCK = 16,
        OVERHEAD_ALERT_INCOMING_DAMAGE = 17,
        OVERHEAD_ALERT_OUTGOING_DAMAGE = 18,
        OVERHEAD_ALERT_DISABLE_RESIST = 19,
        OVERHEAD_ALERT_DEATH = 20,
        OVERHEAD_ALERT_BLOCKED = 21,
        OVERHEAD_ALERT_ITEM_RECEIVED = 22,
        OVERHEAD_ALERT_SHARD = 23,
        OVERHEAD_ALERT_DEADLY_BLOW = 24,
        OVERHEAD_ALERT_FORCE_MISS = 25,
        OVERHEAD_ALERT_AEGIS = 26,
        OVERHEAD_ALERT_DISPEL = 27,
        OVERHEAD_ALERT_BONUS_PURE_DAMAGE = 28,
    };
} // namespace dota_game_enums

namespace dota_game_enums {
    enum class DOTA_RUNES : int {
        DOTA_RUNE_INVALID = -1,
        DOTA_RUNE_DOUBLEDAMAGE = 0,
        DOTA_RUNE_HASTE = 1,
        DOTA_RUNE_ILLUSION = 2,
        DOTA_RUNE_INVISIBILITY = 3,
        DOTA_RUNE_REGENERATION = 4,
        DOTA_RUNE_BOUNTY = 5,
        DOTA_RUNE_ARCANE = 6,
        DOTA_RUNE_WATER = 7,
        DOTA_RUNE_XP = 8,
        DOTA_RUNE_SHIELD = 9,
        DOTA_RUNE_COUNT = 10,
    };
} // namespace dota_game_enums

namespace dota_game_enums {
    enum class DOTA_SHOP_TYPE : int {
        DOTA_SHOP_HOME = 0,
        DOTA_SHOP_SIDE = 1,
        DOTA_SHOP_SECRET = 2,
        DOTA_SHOP_GROUND = 3,
        DOTA_SHOP_SIDE2 = 4,
        DOTA_SHOP_SECRET2 = 5,
        DOTA_SHOP_CUSTOM = 6,
        DOTA_SHOP_NEUTRALS = 7,
        DOTA_SHOP_NONE = 8,
    };
} // namespace dota_game_enums

namespace dota_game_enums {
    enum class DOTA_UNIT_TARGET_FLAGS : int {
        DOTA_UNIT_TARGET_FLAG_NONE = 0,
        DOTA_UNIT_TARGET_FLAG_RANGED_ONLY = 2,
        DOTA_UNIT_TARGET_FLAG_MELEE_ONLY = 4,
        DOTA_UNIT_TARGET_FLAG_DEAD = 8,
        DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES = 16,
        DOTA_UNIT_TARGET_FLAG_NOT_MAGIC_IMMUNE_ALLIES = 32,
        DOTA_UNIT_TARGET_FLAG_INVULNERABLE = 64,
        DOTA_UNIT_TARGET_FLAG_FOW_VISIBLE = 128,
        DOTA_UNIT_TARGET_FLAG_NO_INVIS = 256,
        DOTA_UNIT_TARGET_FLAG_CAN_BE_SEEN = 384,
        DOTA_UNIT_TARGET_FLAG_NOT_ANCIENTS = 512,
        DOTA_UNIT_TARGET_FLAG_PLAYER_CONTROLLED = 1024,
        DOTA_UNIT_TARGET_FLAG_NOT_DOMINATED = 2048,
        DOTA_UNIT_TARGET_FLAG_NOT_SUMMONED = 4096,
        DOTA_UNIT_TARGET_FLAG_NOT_ILLUSIONS = 8192,
        DOTA_UNIT_TARGET_FLAG_NOT_ATTACK_IMMUNE = 16384,
        DOTA_UNIT_TARGET_FLAG_MANA_ONLY = 32768,
        DOTA_UNIT_TARGET_FLAG_CHECK_DISABLE_HELP = 65536,
        DOTA_UNIT_TARGET_FLAG_NOT_CREEP_HERO = 131072,
        DOTA_UNIT_TARGET_FLAG_OUT_OF_WORLD = 262144,
        DOTA_UNIT_TARGET_FLAG_NOT_NIGHTMARED = 524288,
        DOTA_UNIT_TARGET_FLAG_PREFER_ENEMIES = 1048576,
        DOTA_UNIT_TARGET_FLAG_RESPECT_OBSTRUCTIONS = 2097152,
    };
} // namespace dota_game_enums

